include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-nimarkoflow

LUCI_TITLE:=NimarkoFlow
LUCI_DEPENDS:=+luci-base +rpcd +nimarkoflow
LUCI_PKGARCH:=all
PKG_VERSION:=0.1.0
PKG_RELEASE:=1
PKG_LICENSE:=GPL-2.0-or-later
LUCI_MAINTAINER:=nimarko
LUCI_MINIFY_JS:=0

include $(TOPDIR)/feeds/luci/luci.mk
